# Generated by Django 5.0.3 on 2024-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='media/car_images/'),
        ),
    ]
